name: Save Docker Image as Artifact

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Pull Docker image
      run: docker pull envoyproxy/envoy-windows-ltsc2022-dev

    - name: Save Docker image to file
      run: docker save -o envoy-image.tar envoyproxy/envoy-windows-ltsc2022-dev

    - name: Upload Docker image as artifact
      uses: actions/upload-artifact@v3
      with:
        name: envoy-image
        path: envoy-image.tar
