name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-base:
    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push base Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/base-image:latest -f Dockerfile.base .
        docker push ${{ secrets.DOCKER_USERNAME }}/base-image:latest

    - name: Log out from Docker Hub
      run: docker logout

  build-final:
    runs-on: windows-2019
    needs: build-base

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push final Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-windows-image:latest -f Dockerfile .
        docker push ${{ secrets.DOCKER_USERNAME }}/my-windows-image:latest

    - name: Log out from Docker Hub
      run: docker logout